# Uncomment the next line to define a global platform for your project
  platform :ios, '16.0'

  target 'GukbapMinister_Admin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  inhibit_all_warnings!

  # Pods for GukbapMinister_Admin
  # Only pull in Storage features
    pod 'FirebaseUI/Storage', '~> 8.0'
  # Add the Firebase pod for Google Analytics
    pod 'FirebaseAnalytics'

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
    pod 'FirebaseAuth'
    pod 'FirebaseFirestore'
    pod 'FirebaseStorage'
    pod 'FirebaseFirestoreSwift'

    pod 'SDWebImageSwiftUI'
    pod 'Kingfisher', '~> 7.0'
    
   
end
